# Generated by Django 5.2.2 on 2025-08-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stid", models.IntegerField(unique=True)),
                (
                    "name_prefix",
                    models.CharField(
                        choices=[
                            ("นาย.", "นาย."),
                            ("นาง.", "นาง."),
                            ("นางสาว.", "นางสาว."),
                        ],
                        max_length=10,
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
            ],
        ),
    ]
