# Generated by Django 5.2.2 on 2025-08-25 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webpage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="students",
            old_name="lastname",
            new_name="last_name",
        ),
    ]
