# Generated by Django 5.2.2 on 2025-09-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpage", "0002_rename_firstname_students_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
